### ISSUE TITLE
Simple test failed

### ISSUE THREAD

**Issue by drveresh** [ALMaclaine/replace#18]
Hi,

It is failing with several basic and simple use cases, and one of them is:

This command "`$replace 'title' 'test' 404.html`" alone is working fine, but if I put it in a script "build.js", and run it in CLI "node build.js" then throwing the error:

```
<path>/temp/build.js:5
replace 'test' 'title' --count  404.html
        ^^^^^^

SyntaxError: Unexpected string
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Am I missing anything or is it broken?

**Comment by ALMaclaine** [comment]
Can you show more code please?

**Comment by drveresh** [comment]
You may ignore it, I couldn't get that code.

But, I just accidentally ran the sample test code and ended up updating 350+ files in my current project and took long time to undo them.  I sent a PR please review it.

**Comment by ALMaclaine** [comment]
Thank you!
