### ISSUE TITLE
Replacing string that contains a quote using npm script

### ISSUE THREAD

**Issue by pkmnct** [ALMaclaine/replace#9]
I am having trouble using this in an npm script.

When I run the following directly on the cli, it does as I anticipate:
`replace '\"exampleKey\": true' '\"exampleKey\": false' ./example.json`

However, if I put the exact same command in an npm script, it gives me

```
> replace '"exampleKey": true' '"exampleKey": false' ./example.json

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat ''exampleKey:'
    at Object.lstatSync (fs.js:840:3)
    at replacizeFileSync (...\node_modules\replace\replace.js:138:22)   
    at module.exports (...\node_modules\replace\replace.js:79:17)       
    at Object.<anonymous> (...\node_modules\replace\bin\replace.js:42:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
```

I assumed it was due to the unescaped quotes, however when I attempted to escape the quotes in the package.json file like so:
```
scripts: {
   "example": "replace '\\\"exampleKey\\\": true' '\\\"exampleKey\\\": false' ./example.json"
}
```

I still get the same error:
```
> replace '\"exampleKey\": true' '\"exampleKey\": false' ./example.json

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat ''"exampleKey":'
    at Object.lstatSync (fs.js:840:3)
    at replacizeFileSync (...\node_modules\replace\replace.js:138:22)   
    at module.exports (...\node_modules\replace\replace.js:79:17)       
    at Object.<anonymous> (...\node_modules\replace\bin\replace.js:42:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
```

**Comment by pkmnct** [comment]
To follow up, here is the example package.json and example.json:

**package.json:**
```
{
  "name": "example",
  "version": "1.0.0",
  "scripts": {
    "example": "replace '\\\"exampleKey\\\": true' '\\\"exampleKey\\\": false' ./example.json"
  },
  "dependencies": {},
  "devDependencies": {
    "replace": "latest"
  }
}
```

**example.json:**
```
{
  "exampleKey": true
}
```

**Comment by pkmnct** [comment]
I eventually got it to work by not using single quotes, and escaping the quotes as so:

`"example": "replace \"\\\"exampleKey\\\": true\" \"\\\"exampleKey\\\": false\" ./example.json"`
